/*
Ambar OpenAPI Specification

Details about communicating with Ambar.cloud public endpoints. Supported HTTP rest endpoints and their  request and response details.

API version: 2025-04-02
Contact: contact@ambar.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Ambar

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateResourceCredentialsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateResourceCredentialsRequest{}

// UpdateResourceCredentialsRequest The common request for updating credentials of an Ambar resource.
type UpdateResourceCredentialsRequest struct {
	// An Ambar resourceId.
	ResourceId string `json:"resourceId"`
	// The password portion of the credential to update for your resource.
	Password string `json:"password"`
	// The username portion of the credential to update for your resource.
	Username string `json:"username"`
}

type _UpdateResourceCredentialsRequest UpdateResourceCredentialsRequest

// NewUpdateResourceCredentialsRequest instantiates a new UpdateResourceCredentialsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateResourceCredentialsRequest(resourceId string, password string, username string) *UpdateResourceCredentialsRequest {
	this := UpdateResourceCredentialsRequest{}
	this.ResourceId = resourceId
	this.Password = password
	this.Username = username
	return &this
}

// NewUpdateResourceCredentialsRequestWithDefaults instantiates a new UpdateResourceCredentialsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateResourceCredentialsRequestWithDefaults() *UpdateResourceCredentialsRequest {
	this := UpdateResourceCredentialsRequest{}
	return &this
}

// GetResourceId returns the ResourceId field value
func (o *UpdateResourceCredentialsRequest) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *UpdateResourceCredentialsRequest) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *UpdateResourceCredentialsRequest) SetResourceId(v string) {
	o.ResourceId = v
}

// GetPassword returns the Password field value
func (o *UpdateResourceCredentialsRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *UpdateResourceCredentialsRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *UpdateResourceCredentialsRequest) SetPassword(v string) {
	o.Password = v
}

// GetUsername returns the Username field value
func (o *UpdateResourceCredentialsRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UpdateResourceCredentialsRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UpdateResourceCredentialsRequest) SetUsername(v string) {
	o.Username = v
}

func (o UpdateResourceCredentialsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateResourceCredentialsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resourceId"] = o.ResourceId
	toSerialize["password"] = o.Password
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *UpdateResourceCredentialsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resourceId",
		"password",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateResourceCredentialsRequest := _UpdateResourceCredentialsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateResourceCredentialsRequest)

	if err != nil {
		return err
	}

	*o = UpdateResourceCredentialsRequest(varUpdateResourceCredentialsRequest)

	return err
}

type NullableUpdateResourceCredentialsRequest struct {
	value *UpdateResourceCredentialsRequest
	isSet bool
}

func (v NullableUpdateResourceCredentialsRequest) Get() *UpdateResourceCredentialsRequest {
	return v.value
}

func (v *NullableUpdateResourceCredentialsRequest) Set(val *UpdateResourceCredentialsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateResourceCredentialsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateResourceCredentialsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateResourceCredentialsRequest(val *UpdateResourceCredentialsRequest) *NullableUpdateResourceCredentialsRequest {
	return &NullableUpdateResourceCredentialsRequest{value: val, isSet: true}
}

func (v NullableUpdateResourceCredentialsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateResourceCredentialsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


