/*
Ambar OpenAPI Specification

Details about communicating with Ambar.cloud public endpoints. Supported HTTP rest endpoints and their  request and response details.

API version: 2024-04-25
Contact: contact@ambar.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Ambar

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteResourceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteResourceRequest{}

// DeleteResourceRequest The common request for deleting an Ambar resource.
type DeleteResourceRequest struct {
	// An Ambar resourceId.
	ResourceId string `json:"resourceId"`
}

type _DeleteResourceRequest DeleteResourceRequest

// NewDeleteResourceRequest instantiates a new DeleteResourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteResourceRequest(resourceId string) *DeleteResourceRequest {
	this := DeleteResourceRequest{}
	this.ResourceId = resourceId
	return &this
}

// NewDeleteResourceRequestWithDefaults instantiates a new DeleteResourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteResourceRequestWithDefaults() *DeleteResourceRequest {
	this := DeleteResourceRequest{}
	return &this
}

// GetResourceId returns the ResourceId field value
func (o *DeleteResourceRequest) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *DeleteResourceRequest) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *DeleteResourceRequest) SetResourceId(v string) {
	o.ResourceId = v
}

func (o DeleteResourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteResourceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resourceId"] = o.ResourceId
	return toSerialize, nil
}

func (o *DeleteResourceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resourceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteResourceRequest := _DeleteResourceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteResourceRequest)

	if err != nil {
		return err
	}

	*o = DeleteResourceRequest(varDeleteResourceRequest)

	return err
}

type NullableDeleteResourceRequest struct {
	value *DeleteResourceRequest
	isSet bool
}

func (v NullableDeleteResourceRequest) Get() *DeleteResourceRequest {
	return v.value
}

func (v *NullableDeleteResourceRequest) Set(val *DeleteResourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteResourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteResourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteResourceRequest(val *DeleteResourceRequest) *NullableDeleteResourceRequest {
	return &NullableDeleteResourceRequest{value: val, isSet: true}
}

func (v NullableDeleteResourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteResourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


