/*
Ambar OpenAPI Specification

Details about communicating with Ambar.cloud public endpoints. Supported HTTP rest endpoints and their  request and response details.

API version: 2023-12-01
Contact: contact@ambar.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Ambar

import (
	"encoding/json"
)

// checks if the MysqlDataSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MysqlDataSource{}

// MysqlDataSource struct for MysqlDataSource
type MysqlDataSource struct {
	// A case insensitive string for the host on which your MySQL database is running and which Ambar can use to reach the database.
	Hostname string `json:"hostname"`
	// The port number passed as a string which Ambar can use to connect to your MySQL database instance.
	HostPort string `json:"hostPort"`
	// The case sensitive string name of the database on your database host.
	DatabaseName string `json:"databaseName"`
	// The case sensitive string name of the table the DataSource should read.
	TableName string `json:"tableName"`
	// The name of a column where the value for any record is globally unique.
	GloballyUniqueColumn string `json:"globallyUniqueColumn"`
	// The name of a column which monotonically increases on database writes.
	SerialColumn string `json:"serialColumn"`
	// A case sensitive string for the name of the column in your table Ambar can partition on.  Note that partition keys must be unique to a given sequence of records.
	PartitioningColumn string `json:"partitioningColumn"`
	// A case sensitive, comma separated list string of additional columns to be read from  the table into Ambar.
	AdditionalColumns string `json:"additionalColumns"`
	// The server_id value used when starting the MySQL server. See MySQL docs for more information about this value and its defaults when not configured.
	BinLogReplicationServerId string `json:"binLogReplicationServerId"`
	// The hostname of the server responsible for terminating TLS connections for your server,  for example if your server is behind a load balancer.
	TlsTerminationOverrideHost string `json:"tlsTerminationOverrideHost"`
}

// NewMysqlDataSource instantiates a new MysqlDataSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMysqlDataSource(hostname string, hostPort string, databaseName string, tableName string, globallyUniqueColumn string, serialColumn string, partitioningColumn string, additionalColumns string, binLogReplicationServerId string, tlsTerminationOverrideHost string) *MysqlDataSource {
	this := MysqlDataSource{}
	this.Hostname = hostname
	this.HostPort = hostPort
	this.DatabaseName = databaseName
	this.TableName = tableName
	this.GloballyUniqueColumn = globallyUniqueColumn
	this.SerialColumn = serialColumn
	this.PartitioningColumn = partitioningColumn
	this.AdditionalColumns = additionalColumns
	this.BinLogReplicationServerId = binLogReplicationServerId
	this.TlsTerminationOverrideHost = tlsTerminationOverrideHost
	return &this
}

// NewMysqlDataSourceWithDefaults instantiates a new MysqlDataSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMysqlDataSourceWithDefaults() *MysqlDataSource {
	this := MysqlDataSource{}
	return &this
}

// GetHostname returns the Hostname field value
func (o *MysqlDataSource) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *MysqlDataSource) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *MysqlDataSource) SetHostname(v string) {
	o.Hostname = v
}

// GetHostPort returns the HostPort field value
func (o *MysqlDataSource) GetHostPort() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostPort
}

// GetHostPortOk returns a tuple with the HostPort field value
// and a boolean to check if the value has been set.
func (o *MysqlDataSource) GetHostPortOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostPort, true
}

// SetHostPort sets field value
func (o *MysqlDataSource) SetHostPort(v string) {
	o.HostPort = v
}

// GetDatabaseName returns the DatabaseName field value
func (o *MysqlDataSource) GetDatabaseName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DatabaseName
}

// GetDatabaseNameOk returns a tuple with the DatabaseName field value
// and a boolean to check if the value has been set.
func (o *MysqlDataSource) GetDatabaseNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DatabaseName, true
}

// SetDatabaseName sets field value
func (o *MysqlDataSource) SetDatabaseName(v string) {
	o.DatabaseName = v
}

// GetTableName returns the TableName field value
func (o *MysqlDataSource) GetTableName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TableName
}

// GetTableNameOk returns a tuple with the TableName field value
// and a boolean to check if the value has been set.
func (o *MysqlDataSource) GetTableNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TableName, true
}

// SetTableName sets field value
func (o *MysqlDataSource) SetTableName(v string) {
	o.TableName = v
}

// GetGloballyUniqueColumn returns the GloballyUniqueColumn field value
func (o *MysqlDataSource) GetGloballyUniqueColumn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GloballyUniqueColumn
}

// GetGloballyUniqueColumnOk returns a tuple with the GloballyUniqueColumn field value
// and a boolean to check if the value has been set.
func (o *MysqlDataSource) GetGloballyUniqueColumnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GloballyUniqueColumn, true
}

// SetGloballyUniqueColumn sets field value
func (o *MysqlDataSource) SetGloballyUniqueColumn(v string) {
	o.GloballyUniqueColumn = v
}

// GetSerialColumn returns the SerialColumn field value
func (o *MysqlDataSource) GetSerialColumn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SerialColumn
}

// GetSerialColumnOk returns a tuple with the SerialColumn field value
// and a boolean to check if the value has been set.
func (o *MysqlDataSource) GetSerialColumnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SerialColumn, true
}

// SetSerialColumn sets field value
func (o *MysqlDataSource) SetSerialColumn(v string) {
	o.SerialColumn = v
}

// GetPartitioningColumn returns the PartitioningColumn field value
func (o *MysqlDataSource) GetPartitioningColumn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartitioningColumn
}

// GetPartitioningColumnOk returns a tuple with the PartitioningColumn field value
// and a boolean to check if the value has been set.
func (o *MysqlDataSource) GetPartitioningColumnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartitioningColumn, true
}

// SetPartitioningColumn sets field value
func (o *MysqlDataSource) SetPartitioningColumn(v string) {
	o.PartitioningColumn = v
}

// GetAdditionalColumns returns the AdditionalColumns field value
func (o *MysqlDataSource) GetAdditionalColumns() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdditionalColumns
}

// GetAdditionalColumnsOk returns a tuple with the AdditionalColumns field value
// and a boolean to check if the value has been set.
func (o *MysqlDataSource) GetAdditionalColumnsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdditionalColumns, true
}

// SetAdditionalColumns sets field value
func (o *MysqlDataSource) SetAdditionalColumns(v string) {
	o.AdditionalColumns = v
}

// GetBinLogReplicationServerId returns the BinLogReplicationServerId field value
func (o *MysqlDataSource) GetBinLogReplicationServerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BinLogReplicationServerId
}

// GetBinLogReplicationServerIdOk returns a tuple with the BinLogReplicationServerId field value
// and a boolean to check if the value has been set.
func (o *MysqlDataSource) GetBinLogReplicationServerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BinLogReplicationServerId, true
}

// SetBinLogReplicationServerId sets field value
func (o *MysqlDataSource) SetBinLogReplicationServerId(v string) {
	o.BinLogReplicationServerId = v
}

// GetTlsTerminationOverrideHost returns the TlsTerminationOverrideHost field value
func (o *MysqlDataSource) GetTlsTerminationOverrideHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TlsTerminationOverrideHost
}

// GetTlsTerminationOverrideHostOk returns a tuple with the TlsTerminationOverrideHost field value
// and a boolean to check if the value has been set.
func (o *MysqlDataSource) GetTlsTerminationOverrideHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TlsTerminationOverrideHost, true
}

// SetTlsTerminationOverrideHost sets field value
func (o *MysqlDataSource) SetTlsTerminationOverrideHost(v string) {
	o.TlsTerminationOverrideHost = v
}

func (o MysqlDataSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MysqlDataSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hostname"] = o.Hostname
	toSerialize["hostPort"] = o.HostPort
	toSerialize["databaseName"] = o.DatabaseName
	toSerialize["tableName"] = o.TableName
	toSerialize["globallyUniqueColumn"] = o.GloballyUniqueColumn
	toSerialize["serialColumn"] = o.SerialColumn
	toSerialize["partitioningColumn"] = o.PartitioningColumn
	toSerialize["additionalColumns"] = o.AdditionalColumns
	toSerialize["binLogReplicationServerId"] = o.BinLogReplicationServerId
	toSerialize["tlsTerminationOverrideHost"] = o.TlsTerminationOverrideHost
	return toSerialize, nil
}

type NullableMysqlDataSource struct {
	value *MysqlDataSource
	isSet bool
}

func (v NullableMysqlDataSource) Get() *MysqlDataSource {
	return v.value
}

func (v *NullableMysqlDataSource) Set(val *MysqlDataSource) {
	v.value = val
	v.isSet = true
}

func (v NullableMysqlDataSource) IsSet() bool {
	return v.isSet
}

func (v *NullableMysqlDataSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMysqlDataSource(val *MysqlDataSource) *NullableMysqlDataSource {
	return &NullableMysqlDataSource{value: val, isSet: true}
}

func (v NullableMysqlDataSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMysqlDataSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


