/*
Ambar OpenAPI Specification

Details about communicating with Ambar.cloud public endpoints. Supported HTTP rest endpoints and their  request and response details.

API version: 2023-12-01
Contact: contact@ambar.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Ambar

import (
	"encoding/json"
)

// checks if the CreateFilterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFilterRequest{}

// CreateFilterRequest The request properties for creating an Ambar Filter.
type CreateFilterRequest struct {
	// A base64 encoded Ambar Filter. For details about Ambar filter syntax, see our developer docs.
	FilterContents string `json:"filterContents"`
	// The Resource Id of a DataSource resource, which this filter should be applied to by a DataDestination.
	DataSourceId string `json:"dataSourceId"`
	// A description for identifying this Filter.
	Description *string `json:"description,omitempty"`
}

// NewCreateFilterRequest instantiates a new CreateFilterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFilterRequest(filterContents string, dataSourceId string) *CreateFilterRequest {
	this := CreateFilterRequest{}
	this.FilterContents = filterContents
	this.DataSourceId = dataSourceId
	return &this
}

// NewCreateFilterRequestWithDefaults instantiates a new CreateFilterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFilterRequestWithDefaults() *CreateFilterRequest {
	this := CreateFilterRequest{}
	return &this
}

// GetFilterContents returns the FilterContents field value
func (o *CreateFilterRequest) GetFilterContents() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilterContents
}

// GetFilterContentsOk returns a tuple with the FilterContents field value
// and a boolean to check if the value has been set.
func (o *CreateFilterRequest) GetFilterContentsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilterContents, true
}

// SetFilterContents sets field value
func (o *CreateFilterRequest) SetFilterContents(v string) {
	o.FilterContents = v
}

// GetDataSourceId returns the DataSourceId field value
func (o *CreateFilterRequest) GetDataSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DataSourceId
}

// GetDataSourceIdOk returns a tuple with the DataSourceId field value
// and a boolean to check if the value has been set.
func (o *CreateFilterRequest) GetDataSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataSourceId, true
}

// SetDataSourceId sets field value
func (o *CreateFilterRequest) SetDataSourceId(v string) {
	o.DataSourceId = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateFilterRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFilterRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateFilterRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateFilterRequest) SetDescription(v string) {
	o.Description = &v
}

func (o CreateFilterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFilterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filterContents"] = o.FilterContents
	toSerialize["dataSourceId"] = o.DataSourceId
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableCreateFilterRequest struct {
	value *CreateFilterRequest
	isSet bool
}

func (v NullableCreateFilterRequest) Get() *CreateFilterRequest {
	return v.value
}

func (v *NullableCreateFilterRequest) Set(val *CreateFilterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFilterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFilterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFilterRequest(val *CreateFilterRequest) *NullableCreateFilterRequest {
	return &NullableCreateFilterRequest{value: val, isSet: true}
}

func (v NullableCreateFilterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFilterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


