/*
Ambar OpenAPI Specification

Details about communicating with Ambar.cloud public endpoints. Supported HTTP rest endpoints and their  request and response details.

API version: 2023-12-01
Contact: contact@ambar.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Ambar

import (
	"encoding/json"
)

// checks if the ListResourcesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListResourcesResponse{}

// ListResourcesResponse struct for ListResourcesResponse
type ListResourcesResponse struct {
	// The next page available for listing if there is one.
	NextPage *int32 `json:"nextPage,omitempty"`
	Resources []ResourceTypeDetails `json:"resources,omitempty"`
}

// NewListResourcesResponse instantiates a new ListResourcesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListResourcesResponse() *ListResourcesResponse {
	this := ListResourcesResponse{}
	return &this
}

// NewListResourcesResponseWithDefaults instantiates a new ListResourcesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListResourcesResponseWithDefaults() *ListResourcesResponse {
	this := ListResourcesResponse{}
	return &this
}

// GetNextPage returns the NextPage field value if set, zero value otherwise.
func (o *ListResourcesResponse) GetNextPage() int32 {
	if o == nil || IsNil(o.NextPage) {
		var ret int32
		return ret
	}
	return *o.NextPage
}

// GetNextPageOk returns a tuple with the NextPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListResourcesResponse) GetNextPageOk() (*int32, bool) {
	if o == nil || IsNil(o.NextPage) {
		return nil, false
	}
	return o.NextPage, true
}

// HasNextPage returns a boolean if a field has been set.
func (o *ListResourcesResponse) HasNextPage() bool {
	if o != nil && !IsNil(o.NextPage) {
		return true
	}

	return false
}

// SetNextPage gets a reference to the given int32 and assigns it to the NextPage field.
func (o *ListResourcesResponse) SetNextPage(v int32) {
	o.NextPage = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *ListResourcesResponse) GetResources() []ResourceTypeDetails {
	if o == nil || IsNil(o.Resources) {
		var ret []ResourceTypeDetails
		return ret
	}
	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListResourcesResponse) GetResourcesOk() ([]ResourceTypeDetails, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *ListResourcesResponse) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given []ResourceTypeDetails and assigns it to the Resources field.
func (o *ListResourcesResponse) SetResources(v []ResourceTypeDetails) {
	o.Resources = v
}

func (o ListResourcesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListResourcesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextPage) {
		toSerialize["nextPage"] = o.NextPage
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	return toSerialize, nil
}

type NullableListResourcesResponse struct {
	value *ListResourcesResponse
	isSet bool
}

func (v NullableListResourcesResponse) Get() *ListResourcesResponse {
	return v.value
}

func (v *NullableListResourcesResponse) Set(val *ListResourcesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListResourcesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListResourcesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListResourcesResponse(val *ListResourcesResponse) *NullableListResourcesResponse {
	return &NullableListResourcesResponse{value: val, isSet: true}
}

func (v NullableListResourcesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListResourcesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


