/*
Ambar OpenAPI Specification

Details about communicating with Ambar.cloud public endpoints. Supported HTTP rest endpoints and their  request and response details.

API version: 2025-04-02
Contact: contact@ambar.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Ambar

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AmbarServiceException type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AmbarServiceException{}

// AmbarServiceException struct for AmbarServiceException
type AmbarServiceException struct {
	AmbarServiceException string `json:"AmbarServiceException"`
}

type _AmbarServiceException AmbarServiceException

// NewAmbarServiceException instantiates a new AmbarServiceException object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmbarServiceException(ambarServiceException string) *AmbarServiceException {
	this := AmbarServiceException{}
	this.AmbarServiceException = ambarServiceException
	return &this
}

// NewAmbarServiceExceptionWithDefaults instantiates a new AmbarServiceException object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmbarServiceExceptionWithDefaults() *AmbarServiceException {
	this := AmbarServiceException{}
	return &this
}

// GetAmbarServiceException returns the AmbarServiceException field value
func (o *AmbarServiceException) GetAmbarServiceException() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmbarServiceException
}

// GetAmbarServiceExceptionOk returns a tuple with the AmbarServiceException field value
// and a boolean to check if the value has been set.
func (o *AmbarServiceException) GetAmbarServiceExceptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmbarServiceException, true
}

// SetAmbarServiceException sets field value
func (o *AmbarServiceException) SetAmbarServiceException(v string) {
	o.AmbarServiceException = v
}

func (o AmbarServiceException) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AmbarServiceException) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["AmbarServiceException"] = o.AmbarServiceException
	return toSerialize, nil
}

func (o *AmbarServiceException) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"AmbarServiceException",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAmbarServiceException := _AmbarServiceException{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAmbarServiceException)

	if err != nil {
		return err
	}

	*o = AmbarServiceException(varAmbarServiceException)

	return err
}

type NullableAmbarServiceException struct {
	value *AmbarServiceException
	isSet bool
}

func (v NullableAmbarServiceException) Get() *AmbarServiceException {
	return v.value
}

func (v *NullableAmbarServiceException) Set(val *AmbarServiceException) {
	v.value = val
	v.isSet = true
}

func (v NullableAmbarServiceException) IsSet() bool {
	return v.isSet
}

func (v *NullableAmbarServiceException) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmbarServiceException(val *AmbarServiceException) *NullableAmbarServiceException {
	return &NullableAmbarServiceException{value: val, isSet: true}
}

func (v NullableAmbarServiceException) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmbarServiceException) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


