/*
Ambar OpenAPI Specification

Details about communicating with Ambar.cloud public endpoints. Supported HTTP rest endpoints and their  request and response details.

API version: 2023-12-01
Contact: contact@ambar.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Ambar

import (
	"encoding/json"
)

// checks if the CreateFilterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateFilterRequest{}

// CreateFilterRequest The request properties for creating an Ambar Filter.
type CreateFilterRequest struct {
	// The description of record filtering this filter should do. For details see the Filters section in our developer docs.
	FilterContents string `json:"filterContents"`
}

// NewCreateFilterRequest instantiates a new CreateFilterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFilterRequest(filterContents string) *CreateFilterRequest {
	this := CreateFilterRequest{}
	this.FilterContents = filterContents
	return &this
}

// NewCreateFilterRequestWithDefaults instantiates a new CreateFilterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFilterRequestWithDefaults() *CreateFilterRequest {
	this := CreateFilterRequest{}
	return &this
}

// GetFilterContents returns the FilterContents field value
func (o *CreateFilterRequest) GetFilterContents() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilterContents
}

// GetFilterContentsOk returns a tuple with the FilterContents field value
// and a boolean to check if the value has been set.
func (o *CreateFilterRequest) GetFilterContentsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilterContents, true
}

// SetFilterContents sets field value
func (o *CreateFilterRequest) SetFilterContents(v string) {
	o.FilterContents = v
}

func (o CreateFilterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateFilterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filterContents"] = o.FilterContents
	return toSerialize, nil
}

type NullableCreateFilterRequest struct {
	value *CreateFilterRequest
	isSet bool
}

func (v NullableCreateFilterRequest) Get() *CreateFilterRequest {
	return v.value
}

func (v *NullableCreateFilterRequest) Set(val *CreateFilterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFilterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFilterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFilterRequest(val *CreateFilterRequest) *NullableCreateFilterRequest {
	return &NullableCreateFilterRequest{value: val, isSet: true}
}

func (v NullableCreateFilterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFilterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


