/*
Ambar OpenAPI Specification

Details about communicating with Ambar.cloud public endpoints. Supported HTTP rest endpoints and their  request and response details.

API version: 2023-12-01
Contact: contact@ambar.cloud
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Ambar

import (
	"encoding/json"
)

// checks if the ResourceInvalidStateException type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceInvalidStateException{}

// ResourceInvalidStateException struct for ResourceInvalidStateException
type ResourceInvalidStateException struct {
	ResourceInvalidStateException string `json:"ResourceInvalidStateException"`
}

// NewResourceInvalidStateException instantiates a new ResourceInvalidStateException object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceInvalidStateException(resourceInvalidStateException string) *ResourceInvalidStateException {
	this := ResourceInvalidStateException{}
	this.ResourceInvalidStateException = resourceInvalidStateException
	return &this
}

// NewResourceInvalidStateExceptionWithDefaults instantiates a new ResourceInvalidStateException object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceInvalidStateExceptionWithDefaults() *ResourceInvalidStateException {
	this := ResourceInvalidStateException{}
	return &this
}

// GetResourceInvalidStateException returns the ResourceInvalidStateException field value
func (o *ResourceInvalidStateException) GetResourceInvalidStateException() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceInvalidStateException
}

// GetResourceInvalidStateExceptionOk returns a tuple with the ResourceInvalidStateException field value
// and a boolean to check if the value has been set.
func (o *ResourceInvalidStateException) GetResourceInvalidStateExceptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceInvalidStateException, true
}

// SetResourceInvalidStateException sets field value
func (o *ResourceInvalidStateException) SetResourceInvalidStateException(v string) {
	o.ResourceInvalidStateException = v
}

func (o ResourceInvalidStateException) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceInvalidStateException) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ResourceInvalidStateException"] = o.ResourceInvalidStateException
	return toSerialize, nil
}

type NullableResourceInvalidStateException struct {
	value *ResourceInvalidStateException
	isSet bool
}

func (v NullableResourceInvalidStateException) Get() *ResourceInvalidStateException {
	return v.value
}

func (v *NullableResourceInvalidStateException) Set(val *ResourceInvalidStateException) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceInvalidStateException) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceInvalidStateException) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceInvalidStateException(val *ResourceInvalidStateException) *NullableResourceInvalidStateException {
	return &NullableResourceInvalidStateException{value: val, isSet: true}
}

func (v NullableResourceInvalidStateException) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceInvalidStateException) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


